-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.component
(
    id integer NOT NULL,
    component_domain_id character varying,
    component_type_id character varying,
    device_id integer,
    program_id integer,
    "group" character varying,
    version character varying,
    name character varying,
    description character varying,
    PRIMARY KEY (id)
);

CREATE TABLE public.component_capability
(
    id integer NOT NULL,
    component_id integer,
    name character varying,
    description character varying,
    exprassion character varying,
    PRIMARY KEY (id)
);

CREATE TABLE public.component_domain
(
    uid character varying NOT NULL,
    PRIMARY KEY (uid)
);

CREATE TABLE public.component_type
(
    uid character varying NOT NULL,
    PRIMARY KEY (uid)
);

CREATE TABLE public.device
(
    id integer NOT NULL,
    name character varying,
    consumption integer,
    mass integer,
    min_temperature integer,
    max_temperature integer,
    electromagnetic_protection boolean,
    radiological_protection boolean,
    PRIMARY KEY (id)
);

CREATE TABLE public.program
(
    id integer NOT NULL,
    name character varying,
    PRIMARY KEY (id)
);

CREATE TABLE public.program_language
(
    id integer NOT NULL,
    program_id integer,
    programming_language_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.programming_language
(
    id integer NOT NULL,
    name character varying,
    PRIMARY KEY (id)
);

CREATE TABLE public.requirement
(
    id integer NOT NULL,
    name character varying,
    description character varying,
    requirement_category_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.sessions
(
    session_hash character varying,
    login character varying,
    id integer NOT NULL,
    start_date date,
    start_time time without time zone
);

CREATE TABLE public.solution
(
    id integer NOT NULL,
    name character varying,
    PRIMARY KEY (id)
);

CREATE TABLE public.solution_component
(
    id integer NOT NULL,
    solution_id integer,
    used_by integer,
    name character varying,
    PRIMARY KEY (id)
);

CREATE TABLE public.solution_requirement
(
    id integer NOT NULL,
    solution_id integer,
    exprassion character varying,
    PRIMARY KEY (id)
);

CREATE TABLE public.user_groups
(
    id integer NOT NULL,
    group_names character varying,
    PRIMARY KEY (id)
);

CREATE TABLE public.user_roles
(
    id integer NOT NULL,
    roles_type character varying,
    PRIMARY KEY (id)
);

CREATE TABLE public.users
(
    id integer NOT NULL,
    surname character varying,
    department character varying,
    login character varying,
    pass_hash character varying,
    tel character varying,
    email character varying,
    groups character varying,
    role character varying,
    note character varying,
    PRIMARY KEY (id)
);

ALTER TABLE public.component
    ADD FOREIGN KEY (component_domain_id)
    REFERENCES public.component_domain (uid)
    NOT VALID;


ALTER TABLE public.component
    ADD FOREIGN KEY (component_domain_id)
    REFERENCES public.component_domain (uid)
    NOT VALID;


ALTER TABLE public.component
    ADD FOREIGN KEY (component_domain_id)
    REFERENCES public.component_domain (uid)
    NOT VALID;


ALTER TABLE public.component
    ADD FOREIGN KEY (component_type_id)
    REFERENCES public.component_type (uid)
    NOT VALID;


ALTER TABLE public.component
    ADD FOREIGN KEY (component_type_id)
    REFERENCES public.component_type (uid)
    NOT VALID;


ALTER TABLE public.component
    ADD FOREIGN KEY (component_type_id)
    REFERENCES public.component_type (uid)
    NOT VALID;


ALTER TABLE public.component
    ADD FOREIGN KEY (device_id)
    REFERENCES public.device (id)
    NOT VALID;


ALTER TABLE public.component
    ADD FOREIGN KEY (device_id)
    REFERENCES public.device (id)
    NOT VALID;


ALTER TABLE public.component
    ADD FOREIGN KEY (device_id)
    REFERENCES public.device (id)
    NOT VALID;


ALTER TABLE public.component
    ADD FOREIGN KEY (program_id)
    REFERENCES public.program (id)
    NOT VALID;


ALTER TABLE public.component
    ADD FOREIGN KEY (program_id)
    REFERENCES public.program (id)
    NOT VALID;


ALTER TABLE public.component
    ADD FOREIGN KEY (program_id)
    REFERENCES public.program (id)
    NOT VALID;


ALTER TABLE public.component_capability
    ADD FOREIGN KEY (component_id)
    REFERENCES public.component (id)
    NOT VALID;


ALTER TABLE public.program_language
    ADD FOREIGN KEY (program_id)
    REFERENCES public.program (id)
    NOT VALID;


ALTER TABLE public.program_language
    ADD FOREIGN KEY (programming_language_id)
    REFERENCES public.programming_language (id)
    NOT VALID;


ALTER TABLE public.solution_component
    ADD FOREIGN KEY (id)
    REFERENCES public.component (id)
    NOT VALID;


ALTER TABLE public.solution_component
    ADD FOREIGN KEY (solution_id)
    REFERENCES public.solution (id)
    NOT VALID;


ALTER TABLE public.solution_component
    ADD FOREIGN KEY (used_by)
    REFERENCES public.solution_component (id)
    NOT VALID;


ALTER TABLE public.solution_requirement
    ADD FOREIGN KEY (id)
    REFERENCES public.requirement (id)
    NOT VALID;


ALTER TABLE public.solution_requirement
    ADD FOREIGN KEY (solution_id)
    REFERENCES public.solution (id)
    NOT VALID;


ALTER TABLE public.user_groups
    ADD FOREIGN KEY (id)
    REFERENCES public.users (groups)
    NOT VALID;


ALTER TABLE public.user_roles
    ADD FOREIGN KEY (id)
    REFERENCES public.users (role)
    NOT VALID;


ALTER TABLE public.users
    ADD FOREIGN KEY (id)
    REFERENCES public.sessions (login)
    NOT VALID;

END;